import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
  fallback: ["Open_Sans"],
  variable: "--pop",
});

const open_sans = Open_Sans({
  subsets: ["latin"],
  weight: ["400"],
  fallback: ["sans-serif"],
  variable: "--open_sans",
});

export const metadata: Metadata = {
  title: "Huddle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${open_sans.variable}`}>
        {children}
      </body>
    </html>
  );
}
